### ISSUE TITLE
I have found a bug when i launch persona 5 strickers

### ISSUE THREAD

**Issue by X-kuro** [masagrator/ReverseNX-RT#1]
When i activated the plug, the game crashed when it launch, the error code is 2011-0301(0x25a0b).
I didn't find other game crash like this.
You can check my photo:
[luanch](https://imgchr.com/i/NSaf4s)
[error code](https://imgchr.com/i/NSa4Cn)

**Comment by X-kuro** [comment]
If I delete the overlay file ReverseNX-RT-ovl.ovl and ReverseNX-RT.elf, the ReverseNX Tool works well on persona 5 strickers

**Comment by masagrator** [comment]
First, you don't need to delete overlay and plugin. Just use overlay to disable plugin (as stated in first screenshot you have posted)
Second:
![2020061420353700-4EAFD1BE1FD8243F99E01D6EF6C04B23](https://user-images.githubusercontent.com/8557858/84601130-6b728100-ae7e-11ea-8b50-9bdd3bb38026.jpg)

So your configuration is conflicting with plugin. Better check what you have and test what can it be.

**Comment by X-kuro** [comment]
> First, you don't need to delete overlay and plugin. Just use overlay to disable plugin (as stated in first screenshot you have posted)
> Second:
> ![2020061420353700-4EAFD1BE1FD8243F99E01D6EF6C04B23](https://user-images.githubusercontent.com/8557858/84601130-6b728100-ae7e-11ea-8b50-9bdd3bb38026.jpg)
> 
> So your configuration is conflicting with plugin. Better check what you have and test what can it be.

Thank you for your reply, i have checked my plugin, i found the conflict is caused by the old ReverseNX plugin file in SaltySD folder. Thank you very much.
