### ISSUE TITLE
Docked Clock settings in Handheld Mode

### ISSUE THREAD

**Issue by Sevyn13** [masagrator/ReverseNX-RT#13]
Is this supposed to allow docked clock settings in handheld mode with sys-clk? If so, it is not working for me.

**Comment by masagrator** [comment]
It's not.

**Comment by Sevyn13** [comment]
I didn't mean does it changed the clocks. I meant does it allow the clocks to overclock to docked frequencies in handheld mode, like over clocking the gpu passed 460mhz.

**Comment by masagrator** [comment]
No.
