### ISSUE TITLE
How to reactivate after deactivating

### ISSUE THREAD

**Issue by orbitinstasis** [masagrator/ReverseNX-RT#2]
As per the title, I deactivated the plugin in the overlay and was unable to re-activate until i deleted '.bak' that was appended to the (IIRC) RT.elf file.

**Comment by masagrator** [comment]
.bak and .elf files shouldn't exist next to each other. It can mean that after you have deactivated it you installed plugin again, thus creating an issue I didn't predicted in code.

**Comment by orbitinstasis** [comment]
> .bak and .elf files shouldn't exist next to each other. It can mean that after you have deactivated it you installed plugin again, thus creating an issue I didn't predict in code.

it seems the .bak was appended around the same time i selected '(de)activate). I'm not sure how this happened, but i deleted the appended 'bak' and i was able to 'reactivate' the plugin.

can i ask, what is the intended behaviour after clicking (de)activate? should a re-enable button be present? as there was not for me. 

I think the only 'naughty' thing in my setup was the 'latest' (but probably deprecated)  "ReverseNX.elf', which i very recently made sure was deleted.

**Comment by orbitinstasis** [comment]
IIRC the deactivate button dissapeared once deactivated for me, i will try
again soon. can you not 'reactivate' from the overlay?
