### ISSUE TITLE
Update overlay to support 16.0.0

### ISSUE THREAD

**Issue by masagrator** [masagrator/ReverseNX-RT#4]

**Comment by masagrator** [comment]
Pre-release, not tested 

https://github.com/masagrator/ReverseNX-RT/releases/tag/1.0.2

**Comment by masagrator** [comment]
From reports it works. Added as release with bumped version number.

**Comment by RhanCandia** [comment]
It works but my joy cons and Hori grip kept on disconnecting when I use it.

**Comment by masagrator** [comment]
This is an issue with how each game was designed, not with plugin itself.

**Comment by RhanCandia** [comment]
Ah, so that's why I only experience the issue in FE Engage. Thanks for the response.

**Comment by hippydave** [comment]
Not a big deal, but I'm guessing this was release 1.0.2 that added fw16 support, but in the release notes for 1.0.2 it says "Added support for 1.0.2". Only mentioning because the release notes themselves don't specifically mention fw16 support.

**Comment by masagrator** [comment]
> Not a big deal, but I'm guessing this was release 1.0.2 that added fw16 support, but in the release notes for 1.0.2 it says "Added support for 1.0.2". Only mentioning because the release notes themselves don't specifically mention fw16 support.

Shhh, you saw nothing...

**Comment by hippydave** [comment]
> 

🙈
