### ISSUE TITLE
Naruto 2 and jojo's cant start.

### ISSUE THREAD

**Issue by davidzvlc** [masagrator/ReverseNX-RT#6]
I try open this 2 games and I can't get past the screen where it says to press a button to detect the controller, I use switch lite. 
Any idea how it can be solved?.

**Comment by masagrator** [comment]
You must use wireless controllers for those games in docked mode. No easy workaround without patching code by some modder.

**Comment by davidzvlc** [comment]
but even if I put the handeled mode I am still able to move forward,
the screen to choose the controller appears continuously.

**Comment by davidzvlc** [comment]
I found the solution, the problem is with salty nx, in this games i need
hide saltynx folder and i can play.
