### ISSUE TITLE
Overlay not working correctly? 720p screen laid on top of 1080p screen

### ISSUE THREAD

**Issue by Zeph1000** [masagrator/ReverseNX-RT#7]
![20230805_215457](https://github.com/masagrator/ReverseNX-RT/assets/141535682/04083e95-cead-4eac-8892-2361825b6a23)

After going into the overlay, I set Controlled by system to No and set Mode to Handheld and the attached picture is the result. I followed the links and downloaded those zip files and extracted everything onto the root of the SD card, not sure if that's the proper way to set everything up, but I don't get an actual error message, just this result.

The background screen that's 1080p doesn't move with the 720p screen, but does have effects working, I guess looping over two frames.

What is going on and how do I fix it?

**Comment by masagrator** [comment]
Do you use ARCropolis mods?

**Comment by Zeph1000** [comment]
I think I use ARCropolis for custom music and changing character colors for Smash. Other than that, the only other mods I have that I use is the Training Mod Pack, latency slider and less delay mods, which tmk don't use arcropolis.

**Comment by masagrator** [comment]
I would check what happens if you uninstall ARCropolis because hooking mods can conflict with each other.

**Comment by masagrator** [comment]
One year without an ansset.
